In [24]:
import pandas as pd 
import numpy as np  
import pandas as pd

In [25]:
data =  pd.read_csv("data_updated_3_curr_20626_8pm.csv")

In [26]:
data

       Unnamed: 0 geohash  day  ...   temp_hour  geohash_target    demand
0           43522  qp09d4   48  ...  156.076254        0.021006  0.016527
1           49351  qp03wd   48  ...  221.374488        0.201965  0.301006
2            3693  qp0d4t   48  ...   15.435383        0.046749  0.042332
3           39415  qp06p3   48  ...  208.925864        0.011157  0.000090
4            9900  qp09hs   48  ...   47.129411        0.039286  0.075078
...           ...     ...  ...  ...         ...             ...       ...
77294       54590  qp03nq   48  ...   10.145390        0.082357  0.052729
77295       23627  qp03jr   48  ...   63.493879        0.022534  0.040634
77296       47265  qp09fy   48  ...  304.668931        0.036337  0.033208
77297       20665  qp0djk   48  ...  103.948076        0.024678  0.035599
77298       74708  qp095t   49  ...    5.028431        0.010969  0.005190

[77299 rows x 19 columns]

In [27]:
data.columns

Index(['Unnamed: 0', 'geohash', 'day', 'RoadType', 'NumberofLanes',
       'LargeVehicles', 'Landmarks', 'Temperature', 'Weather', 'hour',
       'minute', 'hour_sin', 'hour_cos', 'minute_sin', 'minute_cos',
       'lanes_temp', 'temp_hour', 'geohash_target', 'demand'],
      dtype='object')

In [28]:
data_1 =  data.drop(columns = ['Unnamed: 0'])

In [29]:
data_1

      geohash  day  RoadType  ...   temp_hour  geohash_target    demand
0      qp09d4   48         1  ...  156.076254        0.021006  0.016527
1      qp03wd   48         2  ...  221.374488        0.201965  0.301006
2      qp0d4t   48         1  ...   15.435383        0.046749  0.042332
3      qp06p3   48         1  ...  208.925864        0.011157  0.000090
4      qp09hs   48         1  ...   47.129411        0.039286  0.075078
...       ...  ...       ...  ...         ...             ...       ...
77294  qp03nq   48         1  ...   10.145390        0.082357  0.052729
77295  qp03jr   48         1  ...   63.493879        0.022534  0.040634
77296  qp09fy   48         1  ...  304.668931        0.036337  0.033208
77297  qp0djk   48         1  ...  103.948076        0.024678  0.035599
77298  qp095t   49         1  ...    5.028431        0.010969  0.005190

[77299 rows x 18 columns]

In [30]:
from sklearn.model_selection import train_test_split 

X =  data.drop(columns= ['geohash_target','demand'] ,  axis = 1)
y =  data['demand']

In [31]:
x_train,  x_val,y_train,y_val =  train_test_split(X,y,random_state= 42,test_size= 0.2)

In [32]:
temp  =  x_train.copy()
temp['demand'] =  y_train 

geo_mean =  temp.groupby('geohash')['demand'].mean()

In [33]:
x_train['geohash_target'] =  x_train['geohash'].map(geo_mean)
x_val['geohash_target'] =  x_val['geohash'].map(geo_mean)

In [34]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61839 entries, 43522 to 15795
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      61839 non-null  int64
 1   geohash         61839 non-null  object
 2   day             61839 non-null  int64
 3   RoadType        61839 non-null  int64
 4   NumberofLanes   61839 non-null  int64
 5   LargeVehicles   61839 non-null  int64
 6   Landmarks       61839 non-null  int64
 7   Temperature     61839 non-null  float64
 8   Weather         61839 non-null  int64
 9   hour            61839 non-null  int64
 10  minute          61839 non-null  int64
 11  hour_sin        61839 non-null  float64
 12  hour_cos        61839 non-null  float64
 13  minute_sin      61839 non-null  float64
 14  minute_cos      61839 non-null  float64
 15  lanes_temp      61839 non-null  float64
 16  temp_hour       61839 non-null  float64
 17  geohash_target  61839 non-null  float64
dtypes: float64(8), int64(9), object(1)
memory usage: 9.0+ MB

In [35]:
x_train

       Unnamed: 0 geohash  day  ...  lanes_temp   temp_hour  geohash_target
43522       15935  qp03zk   48  ...   37.404582   74.809165        0.016017
49351       15414  qp09jx   48  ...   46.067924   61.423899        0.024178
3693        62181  qp09fw   48  ...    6.592876  131.857518        0.030832
39415       48679  qp03ty   48  ...   12.051698  156.672069        0.025987
9900        48934  qp0dhe   48  ...   24.827900  161.381351        0.175895
...           ...     ...  ...  ...         ...         ...             ...
6265        50453  qp0d53   48  ...   29.793844  417.113818        0.093889
54886       18653  qp03y7   48  ...   36.766033   91.915082        0.060607
76820       58246  qp03zc   48  ...   27.053758  459.913884        0.139663
860         29474  qp09u5   48  ...   54.053705  144.143214        0.016251
15795       29849  qp09hz   48  ...   50.996637  203.986547        0.012741

[61839 rows x 18 columns]

In [36]:
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error

In [37]:
cat_features = ['geohash']

In [39]:
model =  CatBoostRegressor(
    iterations=5000,
    learning_rate=0.03,
    depth =8,
    loss_function='RMSE',
    eval_metric='RMSE',
    random_seed= 42,
    early_stopping_rounds=200,
    verbose= 100
)

model.fit(x_train,
          y_train,
          eval_set=(x_val,y_val),
          cat_features= cat_features,
          use_best_model= True 
          )

0:	learn: 0.1389502	test: 0.1367513	best: 0.1367513 (0)	total: 65.3ms	remaining: 5m 26s
100:	learn: 0.0416106	test: 0.0417996	best: 0.0417996 (100)	total: 7.02s	remaining: 5m 40s
200:	learn: 0.0376022	test: 0.0382375	best: 0.0382375 (200)	total: 15.1s	remaining: 6m
300:	learn: 0.0359779	test: 0.0369801	best: 0.0369801 (300)	total: 23.1s	remaining: 6m
400:	learn: 0.0347823	test: 0.0361888	best: 0.0361879 (397)	total: 30.7s	remaining: 5m 52s
500:	learn: 0.0335368	test: 0.0352226	best: 0.0352226 (500)	total: 37.8s	remaining: 5m 39s
600:	learn: 0.0325813	test: 0.0345060	best: 0.0345060 (600)	total: 45.4s	remaining: 5m 32s
700:	learn: 0.0318972	test: 0.0340351	best: 0.0340351 (700)	total: 53.1s	remaining: 5m 25s
800:	learn: 0.0312792	test: 0.0336647	best: 0.0336647 (800)	total: 1m	remaining: 5m 16s
900:	learn: 0.0307380	test: 0.0333580	best: 0.0333580 (900)	total: 1m 7s	remaining: 5m 8s
1000:	learn: 0.0302025	test: 0.0330535	best: 0.0330535 (1000)	total: 1m 14s	remaining: 4m 59s
1100:	learn: 0.0297845	test: 0.0328517	best: 0.0328517 (1100)	total: 1m 21s	remaining: 4m 49s
1200:	learn: 0.0293195	test: 0.0326163	best: 0.0326163 (1200)	total: 1m 28s	remaining: 4m 40s
1300:	learn: 0.0289758	test: 0.0324986	best: 0.0324972 (1298)	total: 1m 36s	remaining: 4m 33s
1400:	learn: 0.0286421	test: 0.0323623	best: 0.0323623 (1400)	total: 1m 43s	remaining: 4m 24s
1500:	learn: 0.0283084	test: 0.0322328	best: 0.0322328 (1500)	total: 1m 49s	remaining: 4m 16s
1600:	learn: 0.0280211	test: 0.0321185	best: 0.0321185 (1600)	total: 1m 57s	remaining: 4m 8s
1700:	learn: 0.0277501	test: 0.0320429	best: 0.0320429 (1700)	total: 2m 4s	remaining: 4m
1800:	learn: 0.0274874	test: 0.0319590	best: 0.0319590 (1800)	total: 2m 11s	remaining: 3m 53s
1900:	learn: 0.0272370	test: 0.0318689	best: 0.0318689 (1900)	total: 2m 17s	remaining: 3m 44s
2000:	learn: 0.0270002	test: 0.0317877	best: 0.0317857 (1994)	total: 2m 25s	remaining: 3m 37s
2100:	learn: 0.0267739	test: 0.0316985	best: 0.0316985 (2100)	total: 2m 32s	remaining: 3m 30s
2200:	learn: 0.0265508	test: 0.0316067	best: 0.0316067 (2200)	total: 2m 40s	remaining: 3m 23s
2300:	learn: 0.0263434	test: 0.0315477	best: 0.0315474 (2299)	total: 2m 47s	remaining: 3m 16s
2400:	learn: 0.0261495	test: 0.0314982	best: 0.0314982 (2399)	total: 2m 54s	remaining: 3m 8s
2500:	learn: 0.0259716	test: 0.0314515	best: 0.0314506 (2491)	total: 3m 1s	remaining: 3m 1s
2600:	learn: 0.0257897	test: 0.0314086	best: 0.0314075 (2597)	total: 3m 8s	remaining: 2m 53s
2700:	learn: 0.0256185	test: 0.0313695	best: 0.0313695 (2700)	total: 3m 14s	remaining: 2m 45s
2800:	learn: 0.0254603	test: 0.0313445	best: 0.0313442 (2791)	total: 3m 21s	remaining: 2m 38s
2900:	learn: 0.0252921	test: 0.0313171	best: 0.0313169 (2891)	total: 3m 28s	remaining: 2m 30s
3000:	learn: 0.0251299	test: 0.0312905	best: 0.0312905 (3000)	total: 3m 35s	remaining: 2m 23s
3100:	learn: 0.0249924	test: 0.0312810	best: 0.0312801 (3099)	total: 3m 42s	remaining: 2m 16s
3200:	learn: 0.0248391	test: 0.0312545	best: 0.0312545 (3200)	total: 3m 49s	remaining: 2m 8s
3300:	learn: 0.0246866	test: 0.0312341	best: 0.0312314 (3288)	total: 3m 56s	remaining: 2m 1s
3400:	learn: 0.0245441	test: 0.0312178	best: 0.0312178 (3400)	total: 4m 3s	remaining: 1m 54s
3500:	learn: 0.0244159	test: 0.0312032	best: 0.0312032 (3500)	total: 4m 11s	remaining: 1m 47s
3600:	learn: 0.0242816	test: 0.0311843	best: 0.0311837 (3581)	total: 4m 18s	remaining: 1m 40s
3700:	learn: 0.0241387	test: 0.0311595	best: 0.0311595 (3700)	total: 4m 25s	remaining: 1m 33s
3800:	learn: 0.0240200	test: 0.0311434	best: 0.0311422 (3799)	total: 4m 33s	remaining: 1m 26s
3900:	learn: 0.0238909	test: 0.0311188	best: 0.0311177 (3895)	total: 4m 41s	remaining: 1m 19s
4000:	learn: 0.0237706	test: 0.0311041	best: 0.0311036 (3994)	total: 4m 48s	remaining: 1m 12s
4100:	learn: 0.0236553	test: 0.0310933	best: 0.0310931 (4099)	total: 4m 56s	remaining: 1m 4s
4200:	learn: 0.0235455	test: 0.0310836	best: 0.0310821 (4181)	total: 5m 4s	remaining: 57.9s
4300:	learn: 0.0234251	test: 0.0310693	best: 0.0310688 (4297)	total: 5m 12s	remaining: 50.7s
4400:	learn: 0.0233083	test: 0.0310490	best: 0.0310478 (4393)	total: 5m 19s	remaining: 43.5s
4500:	learn: 0.0232051	test: 0.0310371	best: 0.0310371 (4500)	total: 5m 27s	remaining: 36.3s
4600:	learn: 0.0230974	test: 0.0310240	best: 0.0310240 (4600)	total: 5m 34s	remaining: 29s
4700:	learn: 0.0229812	test: 0.0310070	best: 0.0310070 (4699)	total: 5m 42s	remaining: 21.8s
4800:	learn: 0.0228826	test: 0.0310031	best: 0.0310027 (4744)	total: 5m 49s	remaining: 14.5s
4900:	learn: 0.0227864	test: 0.0309975	best: 0.0309974 (4898)	total: 5m 57s	remaining: 7.22s
4999:	learn: 0.0226771	test: 0.0309848	best: 0.0309846 (4998)	total: 6m 4s	remaining: 0us

bestTest = 0.03098459121
bestIteration = 4998

Shrink model to first 4999 iterations.

CatBoostRegressor(depth=8, early_stopping_rounds=200, eval_metric='RMSE', iterations=5000, learning_rate=0.03, loss_function='RMSE', random_seed=42, verbose=100)

In [40]:
preds =  model.predict(x_val)

In [41]:
rmse =  np.sqrt(mean_squared_error(y_val,preds))

In [42]:
print("RMSE: ",rmse)

RMSE:  0.03098459121676733